### ISSUE TITLE
Green output

### ISSUE THREAD

**Issue by Beyley** [swedishborgie/kinect2pipe#2]
This worked fine on Pop!_OS but on Arch it doesnt seem to do anything but output green, i have both libswscale and libfreenect2 installed and Protonect works fine, im able to compile the app but it doesnt seem to do anything, and i can confirm that the v4l2loopback device is there after running modprobe, no console output is given either [image](https://i.beyleyisnot.moe/cf3e5b4cc3.png)
EDIT: doesnt work in web browsers or anything either

**Comment by swedishborgie** [comment]
So if you're getting a green screen it means that kinect2pipe has initialized and has written a blank frame. If you're not getting video it means either:
* The application can't find your Kinect2.
* The application doesn't have permission to open your Kinect2.
* The application hasn't detected that an application has opened the v4l2loopback device (kinect2pipe doesn't capture video if nothing is watching, since it's pretty CPU intensive decoding MJPEG farmes).
* The application crashed.

The logs should have more information about what's going wrong. If you're running the application as a systemd service you can get the logs via `journalctl`, or you can just run the application directly by doing something like `/usr/bin/kinect2pipe /dev/video0`.

**Comment by Beyley** [comment]
Running the app directly as root and my user account both fail, and the systemd service just fails 
```
May 20 01:19:51 arch systemd[599]: kinect2pipe.service: Main process exited, code=exited, status=1/FAILURE
May 20 01:19:51 arch systemd[599]: kinect2pipe.service: Failed with result 'exit-code'.
``` 
I dont think it is a permission issue with accessing the kinect though as Protonect can find it without root just fine

**Comment by swedishborgie** [comment]
So there are two reasons kinect2pipe could fail with exit code 1:
https://github.com/swedishborgie/kinect2pipe/blob/7c8909070416731f4b967290470a058ab932442b/kinect2pipe.cpp#L45-L53

Based on the fact you've got a green frame, I tend to suspect it's an issue setting up the inotify watcher:
https://github.com/swedishborgie/kinect2pipe/blob/7c8909070416731f4b967290470a058ab932442b/kinect2pipe.cpp#L107-L119

Right now the application doesn't log failures setting up inotify, since I never ran into any issues. Looking at the man pages for the two calls, it seems like the most likely cause of failure would be that you're using a file system that doesn't support inotify or there's in-kernel limits on inotify use.

I just pushed some changes that add additional logging. Can you try pulling and see if you get error messages now? Based on the error you get we should be able to figure out what's going on.

**Comment by Beyley** [comment]
As it turns out i was looking at the start of the logs as i forgot it was reversed, it actually does seem to run in the service like when i do it manually, just still only be a green screen for some reason

Still no console output at all, no errors btw

**Comment by Beyley** [comment]
i didnt mean to mention this issue, and it also went away after some time anyway not sure when
